### PR TITLE
bump runtime to GNOME 40

### PR DESCRIPTION
**Pull request by muelli**
Let's see whether this builds and runs

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by muelli** [comment]
```
go: cannot find main module, but found Gopkg.lock in /run/build/zealcore/go/src/github.com/zealdocs/zealcore
	to create a module there, run:
	go mod init
]2;flatpak-builder: Cleanup zealcoreError: module zealcore: Child process exited with code 1
```

**Comment by lionirdeadman** [comment]
From what I can tell, there needs to be a modification to account for zealdocs/zealcore no longer being there.

This is the file pointing there : https://github.com/jkozera/zealcore/blob/master/zealcore.go#L21
It needs to not do that.

**Comment by jmymay** [comment]
Sorry, I didn't realise anyone is still using it, seems I forgot to mark it as unmaintained on Flathub. I've created an issue at https://github.com/flathub/flathub/issues/2418

The runtime can be upgraded with https://github.com/flathub/io.github.jkozera.ZevDocs/pull/9 - the new Go modules functionality was conflicting with the way zealcore was being built - but I'd rather avoid upgrading the runtime publicly because it could break some functionalities for existing users.

**Pull request closed without merging**
