### PR TITLE
Fix missing gnome-foot.png

### PR DESCRIPTION
**Pull request by jmymay**
bot, build

### CODE REVIEW

**Comment by jmymay** [comment]
bot, build

**Comment by jmymay** [comment]
bot, build

**Comment by TingPing** [comment]
It might make sense for the sources to just be those two files instead of a git repo, lot faster to download.

**Comment by jmymay** [comment]
@TingPing good point, I'll update - thanks!

**Comment by jmymay** [comment]
bot, build

**Comment by jmymay** [comment]
bot, build

**Pull request merged**
